- name: Basic set stats testing
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - set_stats:
        data:
          my_var:
            item0: 1
            item1: "Hello"
            item2: "World"
            item3: "People"